# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OrionGame.ORIONGameLauncher
PackageVersion: 2.0.1
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silencieux
  SilentWithProgress: --silencieux
UpgradeBehavior: install
ProductCode: ORION
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: ORION
  Publisher: ORION
  DisplayVersion: 2.0.1
  ProductCode: ORION
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Sikher-kisa/orion-game-launcher/releases/download/v2.0.1/Installateur-ORION.exe
  InstallerSha256: 6941CFDD23128DB9FA5288CA1F640D03C6E9EF89F4498C07D378F145635959FC
ManifestType: installer
ManifestVersion: 1.12.0
