# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OrionGame.ORIONGameLauncher
PackageVersion: 2.0.0
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silencieux
  SilentWithProgress: --silencieux
UpgradeBehavior: install
ProductCode: ORION
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: ORION
  Publisher: ORION
  DisplayVersion: 2.0.0
  ProductCode: ORION
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Sikher-kisa/orion-game-launcher/releases/download/v2.0.0/Installateur-ORION.exe
  InstallerSha256: 486DC3F787F08166D7F91FB5D1F0B850DE55A0C2D4C8BA63A691D8DEA30AB6BB
ManifestType: installer
ManifestVersion: 1.12.0
